"""
SmartPack Documentation - Part 3: Sections 13 to 19.
LLM Explanation Layer, OTR/WVTR Deep Dive, Complete Technology Stack,
System Architecture, Technical Pipeline Flowchart, API Specifications, and Codebase Structure.
"""

from reportlab.lib import colors
from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
from docs_generator.styles import USABLE_WIDTH, create_callout

def build_section_13_llm_explanation_layer(styles):
    elements = []
    elements.append(Paragraph("13. LLM / Generative AI Layer (Gemini Integration)", styles['SecHeading']))
    elements.append(Paragraph(
        "In `backend/app/services/llm_service.py`, SmartPack integrates **Google Gemini 2.5 Flash** "
        "(with automatic fallback to `gemini-flash-latest`, `gemini-2.5-flash-lite`, and `gemini-1.5-flash`) "
        "as a dynamic, context-aware scientific explanation layer. Crucially, the LLM is **completely decoupled** "
        "from the recommendation decision logic.",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("13.1 Strict Grounding & Anti-Hallucination Architecture", styles['SubSecHeading']))
    elements.append(Paragraph(
        "The LLM does NOT select packaging materials. Instead, after the deterministic rules, ML model, and scoring engine have finalized "
        "the Top 3 recommendations, the user can click <b>'Generate Gemini Narrative'</b>. The system constructs a strictly bounded prompt "
        "containing ONLY the verified facts from the recommendation pipeline:",
        styles['BodyCustom']
    ))
    
    prompt_rules = [
        "<b>Product Composition:</b> Food name, category, moisture %, fat sensitivity, and product pH.",
        "<b>Calculated Requirements:</b> Target oxygen, moisture, and mechanical protection levels.",
        "<b>Selected Candidate Metadata:</b> Material name, packaging format, derived suitability score, and measured OTR/WVTR.",
        "<b>Pipeline Evidence Points:</b> Verified positive evidence points generated by `explanation_engine.py`.",
        "<b>Statutory Document Citations:</b> The exact FSSAI Schedule IV or BIS regulation document and page number.",
        "<b>Strict Injunctions:</b> The system prompt explicitly instructs Gemini: <i>'Be truthful about data limitations: do NOT invent fake OTR or WVTR numbers if unmeasured. Reference statutory compliance under FSSAI Packaging Regulations 2018 or BIS Standards. Keep tone professional, scientific, and concise (under 160 words).'</i>"
    ]
    for r in prompt_rules:
        elements.append(Paragraph(f"• {r}", styles['BulletCustom']))
        
    elements.append(Spacer(1, 4))
    elements.append(Paragraph("13.2 Graceful Degradation Protocol", styles['SubSecHeading']))
    elements.append(Paragraph(
        "If no `GEMINI_API_KEY` is configured in `.env`, the endpoint (`POST /api/explain/gemini`) returns an informational status: "
        "<code>status='UNCONFIGURED'</code>. The application continues functioning seamlessly, displaying the full deterministic "
        "evidence points, scoring weight breakdowns, and statutory citations. The core recommendation system never breaks due to external AI API outages.",
        styles['BodyCustom']
    ))
    
    elements.append(PageBreak())
    return elements


def build_section_14_otr_and_wvtr_deep_dive(styles):
    elements = []
    elements.append(Paragraph("14. Deep Dive: Oxygen & Water Vapor Permeation (OTR / WVTR)", styles['SecHeading']))
    elements.append(Paragraph(
        "Gas and moisture permeation rates are the defining physical parameters of food packaging science. "
        "Because confusion regarding OTR and WVTR is widespread among software engineers and hackathon participants, "
        "this section establishes their fundamental physical definitions and testing parameters.",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("14.1 Physical Definitions and International Units", styles['SubSecHeading']))
    elements.append(Paragraph(
        "<b>Oxygen Transmission Rate (OTR):</b> The quantity of oxygen gas passing through a unit area of parallel surfaces of a plastic film "
        "per unit time, under specified conditions of temperature, relative humidity, and partial pressure gradient. "
        "Standard SI / commercial unit: <b>cc / m² / 24h / atm</b> (or cm³ / m² / day) tested per <b>ASTM D3985</b> (coulometric sensor method).",
        styles['BodyCustom']
    ))
    elements.append(Paragraph(
        "<b>Water Vapor Transmission Rate (WVTR):</b> The steady-state rate at which water vapor permeates through a film under specified "
        "temperature and relative humidity conditions (typically 38°C and 90% RH for tropical climates). "
        "Standard unit: <b>g / m² / 24h</b> tested per <b>ASTM F1249</b> (infrared detection) or <b>IS 5012:1987</b> (gravimetric dish method).",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("14.2 The Physics of Barrier Permeability", styles['SubSecHeading']))
    elements.append(Paragraph(
        "Permeation is governed by the solution-diffusion mechanism: <code>Transmission Rate (TR) = Permeability (P) / Thickness (L) × Δp</code>. "
        "A film with twice the thickness cuts transmission in half. Transmission is NOT a material constant unless normalized by thickness. "
        "Below is the published baseline permeability spectrum across commercial packaging polymers referenced in SmartPack:",
        styles['BodyCustom']
    ))
    
    poly_barrier_data = [
        [Paragraph("<b>Polymer / Material Family</b>", styles['TableHead']), Paragraph("<b>Typical OTR (cc/m2/day @ 23°C)</b>", styles['TableHead']), Paragraph("<b>Typical WVTR (g/m2/day @ 38°C, 90% RH)</b>", styles['TableHead']), Paragraph("<b>Barrier Classification</b>", styles['TableHead']), Paragraph("<b>Commercial Food Application</b>", styles['TableHead'])],
        [Paragraph("Low-Density Polyethylene (LDPE)", styles['TableCellMono']), Paragraph("7,000 - 8,500", styles['TableCell']), Paragraph("15.0 - 20.0", styles['TableCell']), Paragraph("Poor Gas / Moderate Moisture", styles['TableCell']), Paragraph("Fresh milk pouches, bread bags, produce wraps", styles['TableCell'])],
        [Paragraph("High-Density Polyethylene (HDPE)", styles['TableCellMono']), Paragraph("2,000 - 3,000", styles['TableCell']), Paragraph("4.0 - 6.0", styles['TableCell']), Paragraph("Moderate Gas / Good Moisture", styles['TableCell']), Paragraph("Rigid milk jugs, cereal liner bags, edible oil jars", styles['TableCell'])],
        [Paragraph("Biaxially Oriented PP (BOPP)", styles['TableCellMono']), Paragraph("1,500 - 2,000", styles['TableCell']), Paragraph("4.0 - 5.5", styles['TableCell']), Paragraph("Moderate Gas / Good Moisture", styles['TableCell']), Paragraph("Confectionery overwraps, dry snack pouches", styles['TableCell'])],
        [Paragraph("Polyethylene Terephthalate (PET)", styles['TableCellMono']), Paragraph("80 - 120", styles['TableCell']), Paragraph("20.0 - 30.0", styles['TableCell']), Paragraph("Good Gas / Moderate Moisture", styles['TableCell']), Paragraph("Carbonated beverage bottles, blister trays, spice jars", styles['TableCell'])],
        [Paragraph("Polyamide / Nylon-6 (PA)", styles['TableCellMono']), Paragraph("25 - 40", styles['TableCell']), Paragraph("120 - 180 (High)", styles['TableCell']), Paragraph("High Gas / Poor Moisture", styles['TableCell']), Paragraph("Vacuum-packaged cheese, processed meats, punctures", styles['TableCell'])],
        [Paragraph("Ethylene Vinyl Alcohol (EVOH)", styles['TableCellMono']), Paragraph("0.5 - 2.0 (Ultra-High)", styles['TableCell']), Paragraph("30 - 50 (Moisture sensitive)", styles['TableCell']), Paragraph("Ultra-High Gas / Poor Moisture", styles['TableCell']), Paragraph("Co-extruded barrier core for juices, ketchups, meats", styles['TableCell'])],
        [Paragraph("Metallized BOPP / PET (Met-Film)", styles['TableCellMono']), Paragraph("15 - 50", styles['TableCell']), Paragraph("0.8 - 1.5", styles['TableCell']), Paragraph("High Gas / High Moisture", styles['TableCell']), Paragraph("Potato chips, crispy extruded snacks, biscuits", styles['TableCell'])],
        [Paragraph("Aluminium Foil Laminate (Foil)", styles['TableCellMono']), Paragraph("<b>0.00 - 0.05</b> (Hermetic)", styles['TableCell']), Paragraph("<b>0.00 - 0.05</b> (Hermetic)", styles['TableCell']), Paragraph("Total Hermetic Barrier", styles['TableCellBold']), Paragraph("Retort pouches, baby food, pharmaceutical wraps", styles['TableCell'])],
        [Paragraph("Tinplate Can / Glass Container", styles['TableCellMono']), Paragraph("<b>0.00</b> (Absolute Barrier)", styles['TableCell']), Paragraph("<b>0.00</b> (Absolute Barrier)", styles['TableCell']), Paragraph("Total Impermeable Barrier", styles['TableCellBold']), Paragraph("Sterilized canned foods, fruit jams, juices, purees", styles['TableCell'])],
    ]
    t_pb = Table(poly_barrier_data, colWidths=[120, 95, 95, 95, USABLE_WIDTH - 405])
    t_pb.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 2.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_pb)
    
    elements.append(PageBreak())
    return elements


def build_section_15_technology_stack(styles):
    elements = []
    elements.append(Paragraph("15. Complete Technology Stack Specification", styles['SecHeading']))
    elements.append(Paragraph(
        "SmartPack is engineered using a modern, production-grade microservice-ready software architecture. "
        "Every technology present in the codebase was selected to ensure sub-50ms execution speed, strict type safety, "
        "and seamless technical auditability.",
        styles['BodyCustom']
    ))
    
    tech_data = [
        [Paragraph("<b>Layer / Domain</b>", styles['TableHead']), Paragraph("<b>Technology / Framework</b>", styles['TableHead']), Paragraph("<b>Version</b>", styles['TableHead']), Paragraph("<b>Engineering Rationale & Codebase Role</b>", styles['TableHead'])],
        [Paragraph("Backend Framework", styles['TableCellBold']), Paragraph("FastAPI", styles['TableCellMono']), Paragraph("0.115+", styles['TableCell']), Paragraph("High-performance asynchronous REST API framework with native OpenAPI/Swagger documentation.", styles['TableCell'])],
        [Paragraph("Web Server", styles['TableCellBold']), Paragraph("Uvicorn (ASGI)", styles['TableCellMono']), Paragraph("0.34+", styles['TableCell']), Paragraph("Lightweight, lightning-fast ASGI server for production Python deployments.", styles['TableCell'])],
        [Paragraph("Data Contracts", styles['TableCellBold']), Paragraph("Pydantic v2", styles['TableCellMono']), Paragraph("2.10+", styles['TableCell']), Paragraph("Strict schema validation, type enforcement, and automated JSON serialization.", styles['TableCell'])],
        [Paragraph("Machine Learning", styles['TableCellBold']), Paragraph("Scikit-Learn", styles['TableCellMono']), Paragraph("1.6+", styles['TableCell']), Paragraph("Ensemble algorithms (RandomForestRegressor, RandomForestClassifier) and preprocessing pipelines.", styles['TableCell'])],
        [Paragraph("Numerical Math", styles['TableCellBold']), Paragraph("NumPy & Pandas", styles['TableCellMono']), Paragraph("2.2+ / 2.2+", styles['TableCell']), Paragraph("Vectorized tabular dataset processing, log transformations, and CSV parsing.", styles['TableCell'])],
        [Paragraph("Model Persistence", styles['TableCellBold']), Paragraph("Joblib", styles['TableCellMono']), Paragraph("1.4+", styles['TableCell']), Paragraph("Efficient serialization and deserialization of scikit-learn ensemble pipelines.", styles['TableCell'])],
        [Paragraph("LLM Integration", styles['TableCellBold']), Paragraph("Google Gemini API (HTTPX)", styles['TableCellMono']), Paragraph("v1beta REST", styles['TableCell']), Paragraph("Contextual prompt engineering invoking Gemini 2.5 Flash for grounded scientific narratives.", styles['TableCell'])],
        [Paragraph("Frontend Framework", styles['TableCellBold']), Paragraph("React 19 & TypeScript", styles['TableCellMono']), Paragraph("19.0+ / 5.7+", styles['TableCell']), Paragraph("Type-safe, component-driven reactive user interface for recommendation display.", styles['TableCell'])],
        [Paragraph("Build Tooling", styles['TableCellBold']), Paragraph("Vite", styles['TableCellMono']), Paragraph("6.2+", styles['TableCell']), Paragraph("Sub-second hot module replacement (HMR) and optimized ES module bundling.", styles['TableCell'])],
        [Paragraph("Styling & Icons", styles['TableCellBold']), Paragraph("TailwindCSS & Lucide-React", styles['TableCellMono']), Paragraph("3.4+ / 0.475+", styles['TableCell']), Paragraph("Modern responsive light-themed UI styling with accessible visual iconography.", styles['TableCell'])],
        [Paragraph("Static Quality", styles['TableCellBold']), Paragraph("Oxlint / ESLint", styles['TableCellMono']), Paragraph("Latest", styles['TableCell']), Paragraph("Ultra-fast Rust-based static linting ensuring zero dead code, unused imports, or key errors.", styles['TableCell'])],
        [Paragraph("PDF Generation", styles['TableCellBold']), Paragraph("ReportLab", styles['TableCellMono']), Paragraph("5.0.1", styles['TableCell']), Paragraph("Two-pass programmatic canvas rendering publication-quality A4 technical documents.", styles['TableCell'])],
    ]
    t_tech = Table(tech_data, colWidths=[100, 115, 55, USABLE_WIDTH - 270])
    t_tech.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 2.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_tech)
    
    elements.append(PageBreak())
    return elements


def build_section_16_17_system_architecture_and_flows(styles):
    elements = []
    elements.append(Paragraph("16. System Architecture & Component Interaction", styles['SecHeading']))
    elements.append(Paragraph(
        "SmartPack follows a strict layered architecture with decoupled responsibilities. "
        "The diagram below outlines the structural boundary between the presentation tier, API orchestration, "
        "data services, deterministic rule engines, ML inference, and external generative services.",
        styles['BodyCustom']
    ))
    
    # Architecture Table Representation
    arch_box = [
        [Paragraph("<b>PRESENTATION LAYER (React 19 + TypeScript + TailwindCSS)</b><br/>FoodInputForm | RequirementMeters | RecommendationCard | SideBySideComparison | DeveloperDrawer", styles['CalloutTitle'])],
        [Paragraph("↓ <i>JSON Request via HTTP POST /api/analyze</i>", styles['BodyCustomBold'])],
        [Paragraph("<b>API ORCHESTRATION LAYER (FastAPI + Pydantic v2)</b><br/>Input Validation & Sanitization → Session Context Assembly → Exception Interceptors", styles['CalloutTitle'])],
        [Paragraph("↓ <i>Validated Dict Payload</i>", styles['BodyCustomBold'])],
        [Paragraph("<b>DETERMINISTIC KNOWLEDGE & SAFETY GATES</b><br/>"
                   "• DataService (ICMR IFCT 2017 Nutritional Lookup + Post-Harvest Respiration)<br/>"
                   "• RequirementEngine (Physics & Biochemical Preservation Targets)<br/>"
                   "• CandidateGenerator (FSSAI Schedule IV Retrieval + Literature Reference Enrichment)<br/>"
                   "• ConstraintFilter (8 Statutory Hard Prohibitions + Produce Respiration Interlock)", styles['CalloutTitle'])],
        [Paragraph("↓ <i>Surviving Validated Candidates (Zero Regulatory Violations)</i>", styles['BodyCustomBold'])],
        [Paragraph("<b>ALGORITHMIC INFERENCE & MULTI-CRITERIA SCORING</b><br/>"
                   "• FeaturePipeline (Standardized 23-Dimensional Interaction Feature Vector)<br/>"
                   "• ModelLoader & Predictor (Random Forest Regressor 0-100 Score + Classifier Validation)<br/>"
                   "• ScoringEngine (6-Weight Composite Combiner + Critical Barrier Defect Penalty)", styles['CalloutTitle'])],
        [Paragraph("↓ <i>Diversified Top-3 Candidates (Material Families Pruned)</i>", styles['BodyCustomBold'])],
        [Paragraph("<b>EXPLANATION & AUDIT SYNTHESIS LAYER</b><br/>"
                   "• ExplanationEngine (Positive Evidence Checklist, Caveats & Statutory Citations)<br/>"
                   "• LLMService (Google Gemini 2.5 Flash Ground-Truth Evidence Narrative Synthesis)", styles['CalloutTitle'])],
        [Paragraph("↓ <i>Structured Technical Response Contract</i>", styles['BodyCustomBold'])],
        [Paragraph("<b>END-USER DECISION SUPPORT DASHBOARD (React Client UI)</b>", styles['CalloutTitle'])],
    ]
    t_a = Table(arch_box, colWidths=[USABLE_WIDTH])
    t_a.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ('BOX', (0, 0), (-1, -1), 1.0, colors.HexColor("#1E3A8A")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_a)
    
    elements.append(Spacer(1, 8))
    elements.append(Paragraph("17. Complete Technical Execution Flowchart", styles['SecHeading']))
    elements.append(Paragraph(
        "The following sequential flowchart details the step-by-step runtime lifecycle of a recommendation request:",
        styles['BodyCustom']
    ))
    
    flow_steps = [
        [Paragraph("<b>Step</b>", styles['TableHead']), Paragraph("<b>Operation</b>", styles['TableHead']), Paragraph("<b>Decision Gate / Branching Logic</b>", styles['TableHead']), Paragraph("<b>Fallback / Safety Action</b>", styles['TableHead'])],
        [Paragraph("01", styles['TableCellBold']), Paragraph("User Submits Form", styles['TableCellBold']), Paragraph("Pydantic parses AnalyzeRequest. Checks types, bounds, and mandatory inputs.", styles['TableCell']), Paragraph("422 Validation Error returned if invalid.", styles['TableCell'])],
        [Paragraph("02", styles['TableCellBold']), Paragraph("Food Lookup", styles['TableCellBold']), Paragraph("Searches 01_food_dataset.csv. Matches commodity name or category.", styles['TableCell']), Paragraph("Defaults to user-entered moisture & category defaults.", styles['TableCell'])],
        [Paragraph("03", styles['TableCellBold']), Paragraph("Requirement Calc", styles['TableCellBold']), Paragraph("Evaluates fat, moisture delta, transport rigor, respiration class, and shelf life.", styles['TableCell']), Paragraph("Scores 0.0 - 1.0 computed for O2, H2O, Mech, Seal.", styles['TableCell'])],
        [Paragraph("04", styles['TableCellBold']), Paragraph("Candidate Retrieval", styles['TableCellBold']), Paragraph("Filters 14_recommended_packaging.csv by food category (FSSAI Schedule IV).", styles['TableCell']), Paragraph("Retrieves 10-31 raw candidates for category.", styles['TableCell'])],
        [Paragraph("05", styles['TableCellBold']), Paragraph("Regulatory Filter", styles['TableCellBold']), Paragraph("Applies 8 hard constraints (recycled plastics, acid tin, produce respiration).", styles['TableCell']), Paragraph("Disqualified candidates moved to rejected list with reasons.", styles['TableCell'])],
        [Paragraph("06", styles['TableCellBold']), Paragraph("Feasibility Gate", styles['TableCellBold']), Paragraph("Check: Did ANY candidates survive the hard constraint filter?", styles['TableCell']), Paragraph("If 0 survive: Returns NO_COMPATIBLE_PACKAGING.", styles['TableCellBold'])],
        [Paragraph("07", styles['TableCellBold']), Paragraph("Feature Assembly", styles['TableCellBold']), Paragraph("FeaturePipeline builds 23-dimensional vector for each surviving candidate.", styles['TableCell']), Paragraph("Missing OTR/WVTR mapped to log baseline.", styles['TableCell'])],
        [Paragraph("08", styles['TableCellBold']), Paragraph("ML Inference", styles['TableCellBold']), Paragraph("Random Forest Regressor predicts continuous candidate suitability score.", styles['TableCell']), Paragraph("Fallback to 70.0 if model bundle missing.", styles['TableCell'])],
        [Paragraph("09", styles['TableCellBold']), Paragraph("Scoring Engine", styles['TableCellBold']), Paragraph("Computes 6-factor composite score. Evaluates Barrier Defect Penalty.", styles['TableCell']), Paragraph("Reduces score by 35-70% if barrier fails.", styles['TableCellBold'])],
        [Paragraph("10", styles['TableCellBold']), Paragraph("Diversified Top-3", styles['TableCellBold']), Paragraph("Sorts by score. Selects top candidate across distinct material families.", styles['TableCell']), Paragraph("Ensures diverse choices for processor.", styles['TableCell'])],
        [Paragraph("11", styles['TableCellBold']), Paragraph("Audit Payload", styles['TableCellBold']), Paragraph("Assembles evidence, warnings, thickness recommendation, citations.", styles['TableCell']), Paragraph("Returns complete JSON response to frontend.", styles['TableCell'])],
    ]
    t_f = Table(flow_steps, colWidths=[20, 95, 180, USABLE_WIDTH - 295])
    t_f.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 2.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_f)
    
    elements.append(PageBreak())
    return elements


def build_section_18_api_specifications(styles):
    elements = []
    elements.append(Paragraph("18. RESTful API Specifications & Data Contracts", styles['SecHeading']))
    elements.append(Paragraph(
        "SmartPack provides a robust RESTful API implemented in `backend/app/routes/api.py`. "
        "All request and response payloads are validated via Pydantic schemas.",
        styles['BodyCustom']
    ))
    
    api_endpoints = [
        [Paragraph("<b>Endpoint</b>", styles['TableHead']), Paragraph("<b>Method</b>", styles['TableHead']), Paragraph("<b>Description</b>", styles['TableHead']), Paragraph("<b>Status Codes</b>", styles['TableHead'])],
        [Paragraph("/api/health", styles['TableCellMono']), Paragraph("GET", styles['TableCellBold']), Paragraph("Service health check; reports dataset load counts.", styles['TableCell']), Paragraph("200 OK", styles['TableCell'])],
        [Paragraph("/api/foods", styles['TableCellMono']), Paragraph("GET", styles['TableCellBold']), Paragraph("Search foods by keyword (query param `q`). Returns matching ICMR foods.", styles['TableCell']), Paragraph("200 OK", styles['TableCell'])],
        [Paragraph("/api/categories", styles['TableCellMono']), Paragraph("GET", styles['TableCellBold']), Paragraph("Lists all 10 statutory FSSAI Schedule IV food categories.", styles['TableCell']), Paragraph("200 OK", styles['TableCell'])],
        [Paragraph("/api/packaging/materials", styles['TableCellMono']), Paragraph("GET", styles['TableCellBold']), Paragraph("Returns catalog of 26 packaging materials from BIS/FSSAI dataset.", styles['TableCell']), Paragraph("200 OK", styles['TableCell'])],
        [Paragraph("/api/config/weights", styles['TableCellMono']), Paragraph("GET", styles['TableCellBold']), Paragraph("Retrieves active 6 scoring weights (ml, barrier, comp, sl, mech, sust).", styles['TableCell']), Paragraph("200 OK", styles['TableCell'])],
        [Paragraph("/api/config/weights", styles['TableCellMono']), Paragraph("PUT", styles['TableCellBold']), Paragraph("Updates scoring weights; saves to scoring_weights.json.", styles['TableCell']), Paragraph("200 OK / 500 Error", styles['TableCell'])],
        [Paragraph("/api/ml/status", styles['TableCellMono']), Paragraph("GET", styles['TableCellBold']), Paragraph("Returns ML model status, dataset split, metrics (MAE, R2, accuracy).", styles['TableCell']), Paragraph("200 OK", styles['TableCell'])],
        [Paragraph("/api/ml/train", styles['TableCellMono']), Paragraph("POST", styles['TableCellBold']), Paragraph("Triggers retraining of Random Forest Regressor & Classifier on synthetic set.", styles['TableCell']), Paragraph("200 OK", styles['TableCell'])],
        [Paragraph("/api/analyze", styles['TableCellMono']), Paragraph("POST", styles['TableCellBold']), Paragraph("Core recommendation engine. Evaluates commodity and returns Top 3.", styles['TableCell']), Paragraph("200 OK / 422 Error", styles['TableCellBold'])],
        [Paragraph("/api/explain/gemini", styles['TableCellMono']), Paragraph("POST", styles['TableCellBold']), Paragraph("Generates grounded natural-language explanation via Google Gemini.", styles['TableCell']), Paragraph("200 OK", styles['TableCell'])],
    ]
    t_api = Table(api_endpoints, colWidths=[120, 45, USABLE_WIDTH - 235, 70])
    t_api.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 2.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_api)
    
    elements.append(Spacer(1, 6))
    elements.append(Paragraph("18.2 Schema Contract: POST /api/analyze", styles['SubSecHeading']))
    elements.append(Paragraph(
        "<b>Sample Request JSON Payload (Potato Chips):</b>", styles['BodyCustomBold']
    ))
    
    req_json = """{
  "food_name": "Potato Chips",
  "food_category": "Ready-to-eat meal",
  "moisture_level": 2.0,
  "fat_oil_sensitivity": "High",
  "ph": 6.0,
  "respiration_activity": "None",
  "desired_shelf_life_days": 180,
  "storage_temperature_c": 25.0,
  "relative_humidity_pct": 65.0,
  "storage_condition": "Ambient",
  "transport_condition": "Ambient / Road",
  "map_required": "Yes",
  "sustainability_priority": "Standard",
  "preferred_package_type": "Any"
}"""
    t_req_box = Table([[Paragraph(f"<pre>{req_json}</pre>", styles['CodeSnippet'])]], colWidths=[USABLE_WIDTH])
    t_req_box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_req_box)
    
    elements.append(PageBreak())
    return elements


def build_section_19_codebase_structure(styles):
    elements = []
    elements.append(Paragraph("19. Repository Codebase Structure", styles['SecHeading']))
    elements.append(Paragraph(
        "The SmartPack repository is organized into a clean, modular monorepo containing the Python FastAPI backend, "
        "the React 19 TypeScript frontend, datasets, trained model bundles, and test harnesses.",
        styles['BodyCustom']
    ))
    
    code_tree = [
        [Paragraph("<b>Directory / File Path</b>", styles['TableHead']), Paragraph("<b>Architectural Responsibility & Implemented Scope</b>", styles['TableHead'])],
        [Paragraph("backend/app/main.py", styles['TableCellMono']), Paragraph("FastAPI application entrypoint; registers API routes, CORS middleware, startup events.", styles['TableCell'])],
        [Paragraph("backend/app/routes/api.py", styles['TableCellMono']), Paragraph("REST endpoints implementation: /analyze, /foods, /weights, /ml, /explain/gemini.", styles['TableCell'])],
        [Paragraph("backend/app/models/schemas.py", styles['TableCellMono']), Paragraph("Pydantic v2 data models: AnalyzeRequest, ScoringWeightsUpdate, API responses.", styles['TableCell'])],
        [Paragraph("backend/app/services/data_service.py", styles['TableCellMono']), Paragraph("In-memory dataset cache loader; parses 16 CSVs, provides fast indexed lookup.", styles['TableCell'])],
        [Paragraph("backend/app/services/llm_service.py", styles['TableCellMono']), Paragraph("Google Gemini 2.5 Flash client; strictly grounded scientific narrative generator.", styles['TableCell'])],
        [Paragraph("backend/app/logic/requirement_engine.py", styles['TableCellMono']), Paragraph("Biophysical preservation heuristics (calculates O2, H2O, mech, seal, light requirements).", styles['TableCell'])],
        [Paragraph("backend/app/logic/candidate_generator.py", styles['TableCellMono']), Paragraph("Retrieves FSSAI Schedule IV packaging candidates; maps polymer reference data.", styles['TableCell'])],
        [Paragraph("backend/app/logic/constraint_filter.py", styles['TableCellMono']), Paragraph("Enforces 8 deterministic safety interlocks (IS 14534, IS 2991, Produce Interlock).", styles['TableCell'])],
        [Paragraph("backend/app/logic/scoring_engine.py", styles['TableCellMono']), Paragraph("Multi-criteria scoring engine (6 active weights); applies Barrier Defect Penalty.", styles['TableCell'])],
        [Paragraph("backend/app/logic/thickness_engine.py", styles['TableCellMono']), Paragraph("Fick's-law diffusion solver; calculates required film gauge in microns.", styles['TableCell'])],
        [Paragraph("backend/app/logic/explanation_engine.py", styles['TableCellMono']), Paragraph("Material family diversification (_get_family); formats Top 3 output cards & caveats.", styles['TableCell'])],
        [Paragraph("backend/app/ml/preprocessing.py", styles['TableCellMono']), Paragraph("FeaturePipeline; extracts candidate-specific 23-dimensional feature vector.", styles['TableCell'])],
        [Paragraph("backend/app/ml/train.py", styles['TableCellMono']), Paragraph("ModelTrainer; trains RandomForestRegressor & RandomForestClassifier on 600 rows.", styles['TableCell'])],
        [Paragraph("backend/app/ml/predict.py", styles['TableCellMono']), Paragraph("MLPredictor; executes vectorized inference on candidate feature vectors.", styles['TableCell'])],
        [Paragraph("backend/app/ml/model_loader.py", styles['TableCellMono']), Paragraph("Thread-safe singleton caching the deserialized Random Forest model bundle.", styles['TableCell'])],
        [Paragraph("frontend/src/App.tsx", styles['TableCellMono']), Paragraph("Root React component; orchestrates form submission, drawer states, and tab views.", styles['TableCell'])],
        [Paragraph("frontend/src/components/FoodInputForm.tsx", styles['TableCellMono']), Paragraph("Input form with autocompleting food search and slider/dropdown controls.", styles['TableCell'])],
        [Paragraph("frontend/src/components/RecommendationCard.tsx", styles['TableCellMono']), Paragraph("Render cards for Top 3 packaging recommendations with badges and warnings.", styles['TableCell'])],
        [Paragraph("frontend/src/components/ComparisonTable.tsx", styles['TableCellMono']), Paragraph("Side-by-side technical comparison table across Rank 1, 2, and 3 options.", styles['TableCell'])],
        [Paragraph("frontend/src/components/DeveloperDrawer.tsx", styles['TableCellMono']), Paragraph("Telemetry drawer for real-time model retraining, weight adjustment, and funnel audit.", styles['TableCell'])],
        [Paragraph("frontend/src/components/WhyPackagingModal.tsx", styles['TableCellMono']), Paragraph("Scientific explanation modal; triggers dynamic Google Gemini narrative.", styles['TableCell'])],
        [Paragraph("Claude-DataSet/ (01 to 16 CSVs)", styles['TableCellMono']), Paragraph("Curated empirical and regulatory datasets from ICMR, FSSAI, BIS, and ICAR.", styles['TableCell'])],
        [Paragraph("models/packaging_suitability_model.pkl", styles['TableCellMono']), Paragraph("Trained scikit-learn model bundle containing regressor, classifier, and scaler.", styles['TableCell'])],
    ]
    t_tree = Table(code_tree, colWidths=[150, USABLE_WIDTH - 150])
    t_tree.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_tree)
    
    elements.append(PageBreak())
    return elements
