"""
SmartPack Documentation - Part 2: Sections 6 to 12.
Machine Learning, Feature Pipeline, Requirement Engine, Candidate Generation,
Regulatory Filter, Scoring Engine, and Top-3 Recommendation Logic.
"""

from reportlab.lib import colors
from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
from docs_generator.styles import USABLE_WIDTH, create_callout

def build_section_6_machine_learning_pipeline(styles):
    elements = []
    elements.append(Paragraph("6. Machine Learning Architecture & Empirical Realities", styles['SecHeading']))
    elements.append(Paragraph(
        "Machine Learning in SmartPack is implemented via dual ensemble models: a <b>Random Forest Regressor</b> "
        "(`RandomForestRegressor`) predicting a continuous suitability index (0.0 to 1.0, scaled to 0-100) and a "
        "<b>Random Forest Classifier</b> (`RandomForestClassifier`) validating binary acceptance (suitability >= 0.70). "
        "Both models are serialized into a single bundle (`models/packaging_suitability_model.pkl`) alongside scaler objects "
        "and metadata metrics (`models/model_metrics.json`).",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("6.1 The Candidate-Specific Feature Vector Architecture", styles['SubSecHeading']))
    elements.append(Paragraph(
        "A critical innovation in SmartPack's ML design is the use of <b>candidate-specific feature vectors</b>. "
        "Earlier prototypes in AI food packaging attempted to build global classifiers that took only food properties as input "
        "and attempted to predict a multiclass label representing the material name. That architecture suffered from catastrophic failure modes: "
        "it could not generalize to new packaging laminates, could not evaluate trade-offs between packaging variants of the same family, "
        "and produced identical static predictions regardless of candidate barrier properties.",
        styles['BodyCustom']
    ))
    elements.append(Paragraph(
        "In SmartPack v2.0, the ML model evaluates the <b>interaction pair</b>: <code>(Commodity Features + Storage Environment + "
        "Calculated Requirements + Specific Candidate Packaging Properties) → Predicted Suitability Score</code>. "
        "Every candidate packaging material generated from FSSAI Schedule IV produces its own distinct feature vector that reflects "
        "its actual barrier properties (log OTR, log WVTR), mechanical tensile strength, structural format (rigid vs. flexible), "
        "and circularity (recyclability, biodegradability).",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("6.2 Training Pipeline, Hyperparameters & Split", styles['SubSecHeading']))
    elements.append(Paragraph(
        "The model is trained on a synthetic, physics-grounded dataset of <b>600 instances</b> generated by systematically crossing "
        "10 diverse commodity profiles (Carrot, Apple, Potato, Broccoli, Biscuits, Potato Chips, Wheat Flour, Milk Powder, Pickles, RTE Curry) "
        "across varying shelf-life horizons (14 to 365 days), temperatures (2°C to 35°C), and relative humidities (50% to 95%) against "
        "12 representative packaging profiles (CFB boxes, punnets, plastic trays, jute sacks, permeable films, flexible pouches, glass bottles, "
        "tinplate containers, aseptic cartons, metalized BOPP, retort pouches, and kraft paper bags).",
        styles['BodyCustom']
    ))
    
    ml_metrics_data = [
        [Paragraph("<b>Evaluation Metric</b>", styles['TableHead']), Paragraph("<b>Random Forest Regressor</b>", styles['TableHead']), Paragraph("<b>Random Forest Classifier</b>", styles['TableHead']), Paragraph("<b>Engineering Interpretation</b>", styles['TableHead'])],
        [Paragraph("Dataset Rows", styles['TableCellBold']), Paragraph("600 total (450 train / 150 test split)", styles['TableCell']), Paragraph("600 total (450 train / 150 test split)", styles['TableCell']), Paragraph("75% / 25% stratified train-test partition", styles['TableCell'])],
        [Paragraph("Mean Absolute Error (MAE)", styles['TableCellBold']), Paragraph("<b>0.0262</b> (on 0.0 - 1.0 scale)", styles['TableCell']), Paragraph("N/A (Continuous metric)", styles['TableCell']), Paragraph("Average prediction error is ~2.6 suitability points", styles['TableCell'])],
        [Paragraph("Root Mean Squared Error", styles['TableCellBold']), Paragraph("<b>0.0396</b>", styles['TableCell']), Paragraph("N/A (Continuous metric)", styles['TableCell']), Paragraph("Low penalization of large outlier errors", styles['TableCell'])],
        [Paragraph("Coefficient of Det. (R²)", styles['TableCellBold']), Paragraph("<b>0.9765</b> (97.65%)", styles['TableCell']), Paragraph("N/A (Continuous metric)", styles['TableCell']), Paragraph("Model accounts for 97.65% of suitability variance", styles['TableCellBold'])],
        [Paragraph("Classification Accuracy", styles['TableCellBold']), Paragraph("N/A (Regression task)", styles['TableCell']), Paragraph("<b>97.33%</b> (146 / 150 correct)", styles['TableCell']), Paragraph("High fidelity in binary suitability discrimination", styles['TableCellBold'])],
        [Paragraph("Precision & Recall", styles['TableCellBold']), Paragraph("N/A", styles['TableCell']), Paragraph("Precision: <b>98.65%</b> | Recall: <b>96.05%</b>", styles['TableCell']), Paragraph("Minimizes false positives (unsafe packaging recommendations)", styles['TableCell'])],
        [Paragraph("F1-Score", styles['TableCellBold']), Paragraph("N/A", styles['TableCell']), Paragraph("<b>0.9733</b>", styles['TableCell']), Paragraph("Harmonic balance between precision and recall", styles['TableCell'])],
        [Paragraph("Hyperparameters", styles['TableCellBold']), Paragraph("n_estimators=100, max_depth=12, random_state=42", styles['TableCell']), Paragraph("n_estimators=100, max_depth=10, random_state=42", styles['TableCell']), Paragraph("Regularized to prevent overfitting on tabular synthetic rules", styles['TableCell'])],
    ]
    t_ml = Table(ml_metrics_data, colWidths=[110, 110, 110, USABLE_WIDTH - 330])
    t_ml.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 2.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_ml)
    
    elements.append(Spacer(1, 4))
    elements.append(create_callout(
        "CRITICAL DOMAIN NOTICE: SYNTHETIC TRAINING LABELS",
        "The 600 training instances are generated based on codified biophysical principles (Fick's law, respiration kinetics, "
        "and FSSAI Schedule IV recommendations). These rows represent an engineered domain model, NOT thousands of empirical "
        "laboratory storage trials. Training an ML model on synthetic labels codifies expert heuristics into a fast, non-linear scoring function; "
        "it does not substitute for real-world laboratory shelf-life experiments.",
        style_type="warning",
        styles=styles
    ))
    
    elements.append(PageBreak())
    return elements


def build_section_7_feature_engineering(styles):
    elements = []
    elements.append(Paragraph("7. Feature Engineering Pipeline (23 Dimensions)", styles['SecHeading']))
    elements.append(Paragraph(
        "In `backend/app/ml/preprocessing.py`, the `FeaturePipeline` class transforms raw user inputs, calculated requirements, "
        "and candidate packaging specifications into a strictly defined, standardized <b>23-dimensional numerical feature vector</b>. "
        "Below is the complete, verified list of all 23 features utilized by the model.",
        styles['BodyCustom']
    ))
    
    feat_data = [
        [Paragraph("<b>#</b>", styles['TableHead']), Paragraph("<b>Feature Name</b>", styles['TableHead']), Paragraph("<b>Domain</b>", styles['TableHead']), Paragraph("<b>Type / Scale</b>", styles['TableHead']), Paragraph("<b>Importance</b>", styles['TableHead']), Paragraph("<b>Technical Description & Domain Purpose</b>", styles['TableHead'])],
        [Paragraph("1", styles['TableCell']), Paragraph("food_moisture", styles['TableCellMono']), Paragraph("Commodity", styles['TableCell']), Paragraph("Float (0 - 100%)", styles['TableCell']), Paragraph("0.49%", styles['TableCell']), Paragraph("Water content percentage from ICMR IFCT 2017.", styles['TableCell'])],
        [Paragraph("2", styles['TableCell']), Paragraph("food_fat_sensitivity", styles['TableCellMono']), Paragraph("Commodity", styles['TableCell']), Paragraph("Float (0.1, 0.5, 1.0)", styles['TableCell']), Paragraph("0.50%", styles['TableCell']), Paragraph("Sensitivity to lipid oxidation: Low (0.1), Med (0.5), High (1.0).", styles['TableCell'])],
        [Paragraph("3", styles['TableCell']), Paragraph("food_ph", styles['TableCellMono']), Paragraph("Commodity", styles['TableCell']), Paragraph("Float (2.0 - 9.0)", styles['TableCell']), Paragraph("0.18%", styles['TableCell']), Paragraph("Acidity level; determines metal corrosion & acid resistance needs.", styles['TableCell'])],
        [Paragraph("4", styles['TableCell']), Paragraph("respiration_level", styles['TableCellMono']), Paragraph("Commodity", styles['TableCell']), Paragraph("Float (0.0 - 1.0)", styles['TableCell']), Paragraph("0.16%", styles['TableCell']), Paragraph("Produce respiration: None (0.0), Low (0.25), Med (0.5), High (0.8).", styles['TableCell'])],
        [Paragraph("5", styles['TableCell']), Paragraph("shelf_life_days", styles['TableCellMono']), Paragraph("Storage", styles['TableCell']), Paragraph("Float (7 - 365+)", styles['TableCell']), Paragraph("2.37%", styles['TableCell']), Paragraph("Target commercial distribution life requested by processor.", styles['TableCell'])],
        [Paragraph("6", styles['TableCell']), Paragraph("storage_temp", styles['TableCellMono']), Paragraph("Storage", styles['TableCell']), Paragraph("Float (-20 to 45°C)", styles['TableCell']), Paragraph("0.44%", styles['TableCell']), Paragraph("Warehouse storage temperature; accelerates chemical spoilage.", styles['TableCell'])],
        [Paragraph("7", styles['TableCell']), Paragraph("storage_rh", styles['TableCellMono']), Paragraph("Storage", styles['TableCell']), Paragraph("Float (10 - 98%)", styles['TableCell']), Paragraph("0.39%", styles['TableCell']), Paragraph("Ambient relative humidity; governs water vapor partial pressure delta.", styles['TableCell'])],
        [Paragraph("8", styles['TableCell']), Paragraph("req_oxygen_score", styles['TableCellMono']), Paragraph("Requirement", styles['TableCell']), Paragraph("Float (0.0 - 1.0)", styles['TableCell']), Paragraph("0.06%", styles['TableCell']), Paragraph("Calculated oxygen barrier requirement from biochemical heuristics.", styles['TableCell'])],
        [Paragraph("9", styles['TableCell']), Paragraph("req_moisture_score", styles['TableCellMono']), Paragraph("Requirement", styles['TableCell']), Paragraph("Float (0.0 - 1.0)", styles['TableCell']), Paragraph("0.12%", styles['TableCell']), Paragraph("Calculated moisture barrier requirement from moisture delta.", styles['TableCell'])],
        [Paragraph("10", styles['TableCell']), Paragraph("req_mechanical_score", styles['TableCellMono']), Paragraph("Requirement", styles['TableCell']), Paragraph("Float (0.0 - 1.0)", styles['TableCell']), Paragraph("1.62%", styles['TableCell']), Paragraph("Calculated structural requirement based on transport rigor.", styles['TableCell'])],
        [Paragraph("11", styles['TableCell']), Paragraph("req_seal_score", styles['TableCellMono']), Paragraph("Requirement", styles['TableCell']), Paragraph("Float (0.0 - 1.0)", styles['TableCell']), Paragraph("1.06%", styles['TableCell']), Paragraph("Seal hermeticity requirement driven by MAP or long shelf life.", styles['TableCell'])],
        [Paragraph("12", styles['TableCell']), Paragraph("pkg_log_otr", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Float (log10 OTR)", styles['TableCell']), Paragraph("10.53%", styles['TableCellBold']), Paragraph("Log-transformed Oxygen Transmission Rate (cc/m2/day).", styles['TableCellBold'])],
        [Paragraph("13", styles['TableCell']), Paragraph("pkg_log_wvtr", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Float (log10 WVTR)", styles['TableCell']), Paragraph("4.64%", styles['TableCell']), Paragraph("Log-transformed Water Vapor Transmission Rate (g/m2/day).", styles['TableCell'])],
        [Paragraph("14", styles['TableCell']), Paragraph("pkg_is_rigid", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Binary (0.0 / 1.0)", styles['TableCell']), Paragraph("0.73%", styles['TableCell']), Paragraph("Indicator for rigid containers (bottles, cans, boxes, tubs, jars).", styles['TableCell'])],
        [Paragraph("15", styles['TableCell']), Paragraph("pkg_is_flexible", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Binary (0.0 / 1.0)", styles['TableCell']), Paragraph("1.43%", styles['TableCell']), Paragraph("Indicator for flexible formats (pouches, wraps, bags, sachets).", styles['TableCell'])],
        [Paragraph("16", styles['TableCell']), Paragraph("pkg_is_breathable", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Binary (0.0 / 1.0)", styles['TableCell']), Paragraph("2.05%", styles['TableCell']), Paragraph("Indicator for ventilated/breathable packaging (punnets, sacks, mesh).", styles['TableCell'])],
        [Paragraph("17", styles['TableCell']), Paragraph("pkg_is_laminate", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Binary (0.0 / 1.0)", styles['TableCell']), Paragraph("0.42%", styles['TableCell']), Paragraph("Indicator for multi-layer co-extruded or laminated barrier films.", styles['TableCell'])],
        [Paragraph("18", styles['TableCell']), Paragraph("pkg_tensile_mpa", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Float (MPa)", styles['TableCell']), Paragraph("6.17%", styles['TableCellBold']), Paragraph("Ultimate tensile strength from BIS material specifications.", styles['TableCell'])],
        [Paragraph("19", styles['TableCell']), Paragraph("pkg_recyclable", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Binary (0.0 / 1.0)", styles['TableCell']), Paragraph("0.75%", styles['TableCell']), Paragraph("Recyclability indicator conforming to CPCB EPR categories.", styles['TableCell'])],
        [Paragraph("20", styles['TableCell']), Paragraph("pkg_biodegradable", styles['TableCellMono']), Paragraph("Packaging", styles['TableCell']), Paragraph("Binary (0.0 / 1.0)", styles['TableCell']), Paragraph("0.37%", styles['TableCell']), Paragraph("Certified compostability/biodegradability indicator.", styles['TableCell'])],
        [Paragraph("21", styles['TableCell']), Paragraph("barrier_match_oxygen", styles['TableCellMono']), Paragraph("Interaction", styles['TableCell']), Paragraph("Float (0.0 - 1.0)", styles['TableCell']), Paragraph("19.29%", styles['TableCellBold']), Paragraph("Cross-feature: match between required O2 barrier and candidate OTR.", styles['TableCellBold'])],
        [Paragraph("22", styles['TableCell']), Paragraph("barrier_match_moisture", styles['TableCellMono']), Paragraph("Interaction", styles['TableCell']), Paragraph("Float (0.0 - 1.0)", styles['TableCell']), Paragraph("41.31%", styles['TableCellBold']), Paragraph("Cross-feature: match between required moisture barrier and WVTR.", styles['TableCellBold'])],
        [Paragraph("23", styles['TableCell']), Paragraph("respiration_compatibility", styles['TableCellMono']), Paragraph("Interaction", styles['TableCell']), Paragraph("Float (0.0 - 1.0)", styles['TableCell']), Paragraph("4.92%", styles['TableCellBold']), Paragraph("Cross-feature: alignment between produce respiration & package gas exchange.", styles['TableCellBold'])],
    ]
    t_f = Table(feat_data, colWidths=[14, 110, 55, 75, 45, USABLE_WIDTH - 299])
    t_f.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 1.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 1.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 3),
        ('RIGHTPADDING', (0, 0), (-1, -1), 3),
    ]))
    elements.append(t_f)
    
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        "<b>Interpretation of Feature Importances:</b> The empirical feature importance extraction demonstrates that interaction "
        "terms—specifically <code>barrier_match_moisture</code> (41.31%), <code>barrier_match_oxygen</code> (19.29%), and <code>pkg_log_otr</code> (10.53%)—"
        "dominate the model's decision surface. This mirrors commercial packaging science: a package cannot be deemed suitable merely "
        "because of high tensile strength or recyclability if its barrier rates fail to match the product's preservation requirements.",
        styles['BodyCustom']
    ))
    
    elements.append(PageBreak())
    return elements


def build_section_8_requirement_engine(styles):
    elements = []
    elements.append(Paragraph("8. Requirement Generation Engine", styles['SecHeading']))
    elements.append(Paragraph(
        "In `backend/app/logic/requirement_engine.py`, the `RequirementEngine` class executes physics-based and biochemical heuristics "
        "to translate raw food characteristics into six target preservation requirements. Every calculated requirement is assigned a "
        "normalized quantitative score (0.0 to 1.0), a qualitative tier (Low, Medium, High), and an auditable scientific explanation.",
        styles['BodyCustom']
    ))
    
    req_rules = [
        [Paragraph("<b>Preservation Dimension</b>", styles['TableHead']), Paragraph("<b>Biochemical & Physics Heuristic Implementation</b>", styles['TableHead']), Paragraph("<b>Codified Thresholds / Logic</b>", styles['TableHead'])],
        [Paragraph("Oxygen Barrier", styles['TableCellBold']), Paragraph("Driven by fat oxidation sensitivity, requested shelf-life horizon, and ambient temperature acceleration. Base score = 0.2.", styles['TableCell']), Paragraph("High fat adds +0.40; Med fat adds +0.25. Shelf life >180d adds +0.25; >60d adds +0.15. Storage temp >25°C adds +0.10. Score >=0.70 → 'High' barrier required.", styles['TableCell'])],
        [Paragraph("Moisture Barrier", styles['TableCellBold']), Paragraph("Driven by product equilibrium moisture vs. ambient RH partial pressure gradient. Crisp foods (<12% moisture) must keep moisture OUT; wet foods (>60%) must retain moisture.", styles['TableCell']), Paragraph("Moisture <12% adds +0.45 if ambient RH >60%, else +0.35. High moisture (>60%) adds +0.35. Shelf life >90d adds +0.25; >30d adds +0.15. Score >=0.70 → 'High' barrier required.", styles['TableCell'])],
        [Paragraph("Mechanical Robustness", styles['TableCellBold']), Paragraph("Driven by transport logistics rigor and commodity physical crush fragility.", styles['TableCell']), Paragraph("Rough / long-distance road transport adds +0.40; ambient adds +0.20. Fragile foods (biscuits, fresh fruit, snack crisps, eggs) add +0.30. Score >=0.70 → Rigid container or reinforced board mandated.", styles['TableCell'])],
        [Paragraph("Seal Integrity", styles['TableCellBold']), Paragraph("Driven by Modified Atmosphere Packaging (MAP) gas retention and long-term shelf-life hermeticity.", styles['TableCell']), Paragraph("MAP required ('Yes') sets seal score to 0.95 (Hermetic heat seal). Shelf life >90d or liquids/oils sets score to 0.80. Standard dry ambient sets score to 0.30.", styles['TableCell'])],
        [Paragraph("MAP & Gas Exchange", styles['TableCellBold']), Paragraph("Governed by produce respiration activity and commercial gas flushing.", styles['TableCell']), Paragraph("High respiration produces 'Permeable / Breathable'; Medium produce yields 'Semi-permeable / Breathable'. Non-respiring shelf-stable goods yield 'Standard Gas Barrier'.", styles['TableCell'])],
        [Paragraph("Light Protection", styles['TableCellBold']), Paragraph("Protects against photo-induced rancidity and botanical toxicity.", styles['TableCell']), Paragraph("Potatoes, tubers, and onions trigger 'Mandatory Opaque / Light Barrier' (preventing chlorophyll and toxic solanine greening). High fat triggers 'Light-Protective Barrier'.", styles['TableCell'])],
    ]
    t_req = Table(req_rules, colWidths=[105, 230, USABLE_WIDTH - 335])
    t_req.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_req)
    
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        "<b>Distinction Between Implemented and Proposed Rules:</b> All six heuristics in the table above are fully implemented and "
        "active in the codebase. Proposed rules slated for Future Scope include dynamic Arrhenius Q10 temperature-coefficient calculations "
        "for accelerated oxidation kinetics and real-time equilibrium respiration modeling under changing ambient gas concentrations.",
        styles['BodyCustom']
    ))
    
    elements.append(PageBreak())
    return elements


def build_section_9_candidate_generation(styles):
    elements = []
    elements.append(Paragraph("9. Packaging Candidate Generation", styles['SecHeading']))
    elements.append(Paragraph(
        "Candidate generation (`backend/app/logic/candidate_generator.py`) is the primary retrieval stage that produces the pool "
        "of legally viable packaging options. Rather than performing unconstrained heuristic guessing across generic materials, "
        "SmartPack grounds its candidate generation in the statutory ground truth of **FSSAI (Packaging) Regulations 2018, Schedule IV** "
        "(`14_recommended_packaging.csv`, 102 rows).",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("9.1 The Role of FSSAI Schedule IV & Material Enrichment", styles['SubSecHeading']))
    elements.append(Paragraph(
        "FSSAI Schedule IV establishes officially recommended packaging materials and forms across 10 statutory food categories "
        "(Milk & Milk Products, Fats & Oils, Fruit & Vegetable Products, Cereals & Pulses, Meat & Fish Products, Sweets & Confectionery, "
        "Beverages, Spices & Condiments, Ready-to-Eat Foods, and Common Salt). When a user selects a food category, CandidateGenerator "
        "retrieves all Schedule IV rows mapped to that category.",
        styles['BodyCustom']
    ))
    elements.append(Paragraph(
        "Because Schedule IV provides primarily qualitative descriptions (e.g. 'PET/PP/PVC punnets' or 'Corrugated Fibreboard box lined with film'), "
        "CandidateGenerator enriches each raw candidate by performing fuzzy and keyword matching against the **Literature Polymer Reference Table** "
        "(`16_material_barrier_mechanical_reference.csv`, REF-01 to REF-20). This enrichment injects published OTR, WVTR, tensile strength, "
        "and circularity metadata into the candidate record.",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("9.2 Fick's-Law Film Thickness Recommendation", styles['SubSecHeading']))
    elements.append(Paragraph(
        "For flexible polymer candidates, CandidateGenerator invokes `thickness_engine.py` to calculate the minimum film thickness gauge "
        "(in microns) required to satisfy the product's calculated oxygen and moisture barrier thresholds, using Fick's first law of diffusion: "
        "<code>Required Thickness = (Reference Permeability P) / (Target Transmission Rate TR)</code>. "
        "The solver selects the nearest standard commercial film gauge (25, 37, 50, 75, or 100 microns). For rigid or hermetic formats "
        "(glass, tinplate, foil composites), the engine transparently returns <i>'N/A — rigid, impermeable format'</i>.",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("9.3 Known Architectural Limitation: Category Granularity", styles['SubSecHeading']))
    elements.append(Paragraph(
        "A critical limitation identified during pipeline audit is that FSSAI Schedule IV groups foods into broad regulatory categories. "
        "For example, 'Fruit & Vegetable products' encompasses fresh apples, carrots, raw potatoes, fruit jams, and tomato purees. "
        "Consequently, candidate generation initially retrieves an identical raw candidate pool (13-15 options) for both fresh carrots "
        "and processed pickles. This demonstrates why the **Regulatory Constraint Filter** and **Produce Respiration Interlock** "
        "(Section 10) are strictly necessary to prune incompatible candidates before scoring.",
        styles['BodyCustom']
    ))
    
    elements.append(PageBreak())
    return elements


def build_section_10_regulatory_constraint_filter(styles):
    elements = []
    elements.append(Paragraph("10. Regulatory Hard Constraint Filter & Safety Interlocks", styles['SecHeading']))
    elements.append(Paragraph(
        "In `backend/app/logic/constraint_filter.py`, the `ConstraintFilter` class enforces non-negotiable statutory prohibitions, "
        "chemical incompatibilities, and physical safety interlocks. It strictly segregates <b>Hard Constraints</b> (binary gatekeepers) "
        "from <b>Soft Scores</b> (preference-based mathematical optimizations).",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("10.1 Hard Constraints vs. Soft Scores", styles['SubSecHeading']))
    elements.append(Paragraph(
        "A <b>Hard Constraint</b> is a binary veto: if a candidate packaging option violates a statutory law or biological safety limit, "
        "it is immediately evicted from the pipeline. It is not penalized with a lower score; it receives a rejection status (`HARD_CONSTRAINT_FILTER`) "
        "and is completely barred from ranking. A <b>Soft Score</b>, by contrast, evaluates trade-offs (e.g. balancing a slightly higher barrier "
        "against an improved recyclability profile). Regulatory constraints must always precede scoring to prevent an illegal material from "
        "achieving a high rank due to high recyclability or low cost.",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("10.2 The Eight Deterministic Safety Interlocks", styles['SubSecHeading']))
    
    filter_data = [
        [Paragraph("<b>#</b>", styles['TableHead']), Paragraph("<b>Interlock Name</b>", styles['TableHead']), Paragraph("<b>Statutory / Physics Basis</b>", styles['TableHead']), Paragraph("<b>Veto Condition & Rejection Trigger</b>", styles['TableHead'])],
        [Paragraph("1", styles['TableCellBold']), Paragraph("Recycled Plastics Ban", styles['TableCellBold']), Paragraph("FSSAI Reg 4(4) & IS 14534:1998", styles['TableCell']), Paragraph("Rejects any material containing post-consumer recycled plastic for direct food contact.", styles['TableCell'])],
        [Paragraph("2", styles['TableCellBold']), Paragraph("Base Wax Paper Ban", styles['TableCellBold']), Paragraph("IS 2991:1988 Clause 1.1", styles['TableCell']), Paragraph("Explicitly prohibits base paper for waxed paper from confectionery and direct food wrapping.", styles['TableCell'])],
        [Paragraph("3", styles['TableCellBold']), Paragraph("Acid Etching Interlock", styles['TableCellBold']), Paragraph("IS 5837 Internal Lacquering Mandate", styles['TableCell']), Paragraph("Prohibits plain unlacquered tinplate for foods with pH < 4.5 to prevent tin dissolution.", styles['TableCell'])],
        [Paragraph("4", styles['TableCellBold']), Paragraph("MAP Hermeticity Interlock", styles['TableCellBold']), Paragraph("Gas Flushing Physical Containment", styles['TableCell']), Paragraph("Rejects porous or unsealed materials (jute, mesh, unlined paperboard) when MAP is demanded.", styles['TableCell'])],
        [Paragraph("5", styles['TableCellBold']), Paragraph("Format Preference Interlock", styles['TableCellBold']), Paragraph("User Packaging Specification", styles['TableCell']), Paragraph("Enforces user-selected physical format (filtering rigid vs. flexible options).", styles['TableCell'])],
        [Paragraph("6", styles['TableCellBold']), Paragraph("Strict Sustainability Interlock", styles['TableCellBold']), Paragraph("Zero-Plastic Mandate", styles['TableCell']), Paragraph("Rejects non-recyclable multilayer plastics when user specifies strict zero-plastic priority.", styles['TableCell'])],
        [Paragraph("7", styles['TableCellBold']), Paragraph("Produce Respiration Interlock", styles['TableCellBold']), Paragraph("Post-Harvest Anaerobiosis Prevention", styles['TableCell']), Paragraph("Prohibits airtight hermetic metal cans, glass jars, and retort pouches for live respiring produce.", styles['TableCellBold'])],
        [Paragraph("8", styles['TableCellBold']), Paragraph("Snack Dispensing Interlock", styles['TableCellBold']), Paragraph("Physical Geometry & Jamming", styles['TableCell']), Paragraph("Prohibits narrow-neck bottles for planar crispy snacks (potato chips, crackers, wafers).", styles['TableCellBold'])],
    ]
    t_filt = Table(filter_data, colWidths=[14, 110, 120, USABLE_WIDTH - 244])
    t_filt.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 2.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_filt)
    
    elements.append(Spacer(1, 4))
    elements.append(create_callout(
        "AUDIT DISCLOSURE: WHY INTERLOCKS 7 & 8 WERE INTRODUCED",
        "During baseline technical testing, SmartPack observed that fresh carrots and apples received metal cans and glass bottles in their "
        "candidate pools because FSSAI Schedule IV lists 'Fruit & Vegetable products' as a broad category (covering both fresh produce and "
        "canned fruits). Similarly, potato chips received 'Glass bottles' because snacks were mapped to processed food containers. "
        "The introduction of the Produce Respiration Interlock and Snack Dispensing Interlock permanently resolved this bug, "
        "ensuring biological and physical realism.",
        style_type="tip",
        styles=styles
    ))
    
    elements.append(PageBreak())
    return elements


def build_section_11_scoring_engine(styles):
    elements = []
    elements.append(Paragraph("11. Multi-Criteria Technical Scoring Engine", styles['SecHeading']))
    elements.append(Paragraph(
        "Candidates surviving the hard constraint filter are scored and ranked by `backend/app/logic/scoring_engine.py`. "
        "The engine computes a multi-dimensional suitability index across six technical dimensions. All weights are user-configurable "
        "via `PUT /api/config/weights` and persisted in `config/scoring_weights.json`.",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("11.1 Active Scoring Weights & Dimensions", styles['SubSecHeading']))
    
    weights_data = [
        [Paragraph("<b>Scoring Dimension</b>", styles['TableHead']), Paragraph("<b>Active Weight</b>", styles['TableHead']), Paragraph("<b>Evaluation Methodology & Source</b>", styles['TableHead'])],
        [Paragraph("ML Model Score (ml_score)", styles['TableCellBold']), Paragraph("<b>0.25 (25%)</b>", styles['TableCellBold']), Paragraph("Inference score from candidate-specific Random Forest Regressor (0.0 to 1.0) evaluating 23-feature vector.", styles['TableCell'])],
        [Paragraph("Barrier Performance (barrier_score)", styles['TableCellBold']), Paragraph("<b>0.25 (25%)</b>", styles['TableCellBold']), Paragraph("Physical evaluation of oxygen and moisture transmission rates against calculated preservation targets.", styles['TableCell'])],
        [Paragraph("Chemical Compatibility (compatibility_score)", styles['TableCellBold']), Paragraph("<b>0.15 (15%)</b>", styles['TableCellBold']), Paragraph("FSSAI Schedule IV statutory listing, inertness of contact layer, and light-protective opacity.", styles['TableCell'])],
        [Paragraph("Shelf-Life Preservation (shelf_life_score)", styles['TableCellBold']), Paragraph("<b>0.15 (15%)</b>", styles['TableCellBold']), Paragraph("Empirical shelf-life benchmark comparison. Applies validation penalty if target days exceed source benchmark.", styles['TableCell'])],
        [Paragraph("Mechanical Robustness (mechanical_score)", styles['TableCellBold']), Paragraph("<b>0.10 (10%)</b>", styles['TableCellBold']), Paragraph("Tensile strength (MPa) and burst index from BIS standards matched against transport rigor.", styles['TableCell'])],
        [Paragraph("Sustainability & Circularity (sustainability_score)", styles['TableCellBold']), Paragraph("<b>0.10 (10%)</b>", styles['TableCellBold']), Paragraph("Recyclability under CPCB EPR categories, mono-material purity, and certified compostability.", styles['TableCell'])],
        [Paragraph("<b>TOTAL COMPOSITE SUM</b>", styles['TableCellBold']), Paragraph("<b>1.00 (100%)</b>", styles['TableCellBold']), Paragraph("Strictly normalized linear combination. Weights sum to exactly 1.0.", styles['TableCellBold'])],
    ]
    t_w = Table(weights_data, colWidths=[140, 75, USABLE_WIDTH - 215])
    t_w.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]))
    elements.append(t_w)
    
    elements.append(Spacer(1, 6))
    elements.append(Paragraph("11.2 The Critical Barrier Defect Penalty", styles['SubSecHeading']))
    elements.append(Paragraph(
        "A classic failure of naive linear scoring systems is that a packaging material with catastrophic barrier performance "
        "(e.g. an unlined jute bag for potato chips) can still achieve a high composite score if it scores 100% on sustainability, "
        "100% on mechanical strength, and 90% on compatibility. In food science, **barrier failure is non-compensable**.",
        styles['BodyCustom']
    ))
    elements.append(Paragraph(
        "To prevent dangerous ranking inversions, SmartPack introduces a multiplicative **Barrier Defect Penalty**:<br/>"
        "<code>Composite = (w_ml·S_ml + w_bar·S_bar + w_comp·S_comp + w_sl·S_sl + w_mech·S_mech + w_sust·S_sust) × Penalty</code><br/>"
        "For lipid-sensitive or moisture-sensitive foods: if <code>barrier_score <= 0.20</code>, <code>Penalty = 0.30</code> (70% score reduction). "
        "If <code>barrier_score <= 0.40</code>, <code>Penalty = 0.65</code> (35% score reduction). "
        "This ensures that inadequate barrier packaging can never achieve a Top 3 recommendation for sensitive commodities.",
        styles['BodyCustom']
    ))
    
    elements.append(PageBreak())
    return elements


def build_section_12_top3_recommendation_logic(styles):
    elements = []
    elements.append(Paragraph("12. Top-3 Recommendation & Diversification Logic", styles['SecHeading']))
    elements.append(Paragraph(
        "In `backend/app/logic/explanation_engine.py`, SmartPack selects the final Top 3 recommendations from the sorted pool "
        "of scored candidates. A naive selection of the top 3 highest scores often produces three virtually identical variants of the same "
        "format (e.g. three slightly different gauges of polypropylene pouches). SmartPack solves this via **Material Family Diversification**.",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("12.1 Material Family Diversification Algorithm", styles['SubSecHeading']))
    elements.append(Paragraph(
        "Every surviving candidate is classified into one of seven distinct packaging families via `_get_family(cand)`: "
        "<b>1. Glass</b> (bottles, jars), <b>2. Metal</b> (tinplate, aluminium cans, TFS), <b>3. Composite / Carton</b> (CFB boxes, paperboard), "
        "<b>4. Foil / Aseptic</b> (multilayer foil laminates, retort pouches), <b>5. Thermoformed Tray</b> (punnets, rigid trays), "
        "<b>6. Flexible Pouch</b> (polyethylene pouches, films, wrappers), and <b>7. Rigid Plastic</b> (HDPE jars, PET containers).",
        styles['BodyCustom']
    ))
    elements.append(Paragraph(
        "The selection loop iterates through the sorted candidates, selecting the highest-ranking candidate from distinct material families. "
        "This guarantees that the food processor receives genuinely diverse commercial alternatives (e.g. Rank 1: High-barrier flexible pouch; "
        "Rank 2: Rigid thermoformed container; Rank 3: Sustainable paperboard composite).",
        styles['BodyCustom']
    ))
    
    elements.append(Paragraph("12.2 Recommendation Structure & Data Labels", styles['SubSecHeading']))
    elements.append(Paragraph(
        "Every recommendation card rendered on the frontend displays transparent origin labels indicating the exact provenance of the data: "
        "<code>DATABASE VALUE</code> (direct empirical citation from FSSAI or ICAR), <code>DERIVED SCORE</code> (calculated composite metric), "
        "<code>CALCULATED REQUIREMENT</code> (biophysical heuristic output), or <code>ML PREDICTION</code> (Random Forest output). "
        "Unmeasured technical properties display <i>'Not available'</i> in strict compliance with scientific integrity.",
        styles['BodyCustom']
    ))
    
    elements.append(PageBreak())
    return elements
